### ISSUE TITLE
Output file name pattern shouldn't require '%s'

### ISSUE THREAD

**Issue by xcapdevila** [xcapdevila/credit-card-generator#1]
**Context**

Currently, output file pattern property is expected to have one '%s' to be replaced by the current date time.

`Input: "test_cards_%s.csv"`
`Output: "test_cards_2021_05_31_10_37_32.csv"`

As it is, if you omit the '%s':
`Input: "test_cards.csv"`
`Output: Exception`

**Expected behaviour**

Change the technical approach from String.format to String.replaceAll and define a keyword to be replaced (such as "${now}").

`Input: "test_cards_${now}.csv"`
`Output: "test_cards_2021_05_31_10_37_32.csv"`

`Input: "test_cards.csv"`
`Output: "test_cards.csv"`

**Comment by shreegilliorkar** [comment]
@xcapdevila , Can you please share the details of this issue and in which file i have to look for it.

**Comment by xcapdevila** [comment]
Hi @Shree-Gillorkar, thanks for contributing!

The main logic is done in [CreditCardGenerator.java](https://github.com/xcapdevila/credit-card-generator/blob/main/src/main/java/io/capdevila/creditcard/generator/CreditCardGenerator.java).

Also its tests must be updated [CreditCardGeneratorTests.java](https://github.com/xcapdevila/credit-card-generator/blob/main/src/test/java/io/capdevila/creditcard/generator/CreditCardGeneratorTests.java).

**Comment by shreegilliorkar** [comment]
@xcapdevila , Okay Thank you. I will try to sort this out, if any doubt i will contact you.

**Comment by shreegilliorkar** [comment]
I updated the code in CreditCardGeneratorTests.java, can you please look into it, and please let me know if any changes are required.

**Comment by israeldago** [comment]
Hello @Shree-Gillorkar , i like the idea of this project and i would like also to contribuite :)

**Comment by israeldago** [comment]
Hello @xcapdevila, 
I've just submitted a PR #4 , hoping that it will fulfull the requirement.
Thank you in advance for taking a look :)
