### ISSUE TITLE
Output pattern must be changed to keywords

### ISSUE THREAD

**Issue by xcapdevila** [xcapdevila/credit-card-generator#2]
**Context**

Currently, output pattern property is expected to have four '%s' to be replaced by the generated pan, cvv, expiration date and the issuer name.

`Input: "%s,%s,%s,%s"`
`Output: "PAN,CVV,EXP_DATE,ISSUER_NAME"`

As it is, if you omit any '%s':
`Input: "%s,%s,%s"`
`Output: Exception`

**Expected behaviour**

Change the technical approach from String.format to String.replaceAll and define keywords to be replaced (such as "${pan}").

`Input: "${pan},${cvv},${expDate},${issuerName}"`
`Output: "PAN,CVV,EXP_DATE,ISSUER_NAME"`

`Input: "${pan};${expDate};${cvv}"`
`Output: "PAN;EXP_DATE;CVV"`

**Comment by shreegilliorkar** [comment]
Hey @xcapdevila , I would like to contribute in this project. Can you please tell the details of the issue like in which file i have to look for the code and work on this issue.

**Comment by xcapdevila** [comment]
Hi @Shree-Gillorkar, thanks for contributing!

The main logic is done in [CreditCardGenerator.java](https://github.com/xcapdevila/credit-card-generator/blob/main/src/main/java/io/capdevila/creditcard/generator/CreditCardGenerator.java).

Also its tests must be updated [CreditCardGeneratorTests.java](https://github.com/xcapdevila/credit-card-generator/blob/main/src/test/java/io/capdevila/creditcard/generator/CreditCardGeneratorTests.java).

**Comment by shreegilliorkar** [comment]
@xcapdevila , Okay Thank you. I will try to sort this out, if any doubt i will contact you.

**Comment by shreegilliorkar** [comment]
@xcapdevila , Please have a look and please let me know if any changes are required.

**Comment by israeldago** [comment]
Hello @xcapdevila,
I took a shot with this issue also via the PR #6  :)
This PR maily contains : 
1. Use of predefined keywords for the output pattern
1. Adjusted CreditCardGeneratorTests.java for the use of predefined keywords for the output pattern
1. Updated README.md 
1. Pom dump version

At disposal for any adjustments if needed.
@israeldago

**Comment by xcapdevila** [comment]
@israeldago awesome! Many thanks!
